# Website / endpoint probing targets

- targets:
    - https://www.jlarrymortgages.com
  labels:
    tenant: internal
    instance: mortgage-website
    role: website
    environment: production

- targets:
    - https://www.irinobservability.com
  labels:
    tenant: Irin
    instance: irin-website
    role: website
    environment: production

- targets:
    - https://monitor.irinobservability.com
  labels:
    tenant: Irin
    instance: irin-monitor-primary
    role: website
    environment: production

- targets:
    - https://replica.irinobservability.com
  labels:
    tenant: Irin
    instance: irin-monitor-replica
    role: website
    environment: production
