## CPU Temperature Exporter for Physical Servers Running Proxmox

- targets:
    - 192.0.2.10:8001
  labels:
    tenant: homelab
    cluster: homelab-physical
    instance: proxmox01
    environment: server
    platform: proxmox_ve
    host: proxmox01
    role: proxmox_ve
    exporter: cpu_temp_exporter

- targets:
    - 192.0.2.11:8001
  labels:
    tenant: homelab
    cluster: homelab-physical
    instance: proxmox02
    environment: server
    platform: proxmox_ve
    host: proxmox02
    role: proxmox_ve
    exporter: cpu_temp_exporter

- targets:
    - 192.0.2.12:8001
  labels:
    tenant: homelab
    cluster: homelab-physical
    instance: proxmox03
    environment: server
    platform: proxmox_ve
    host: proxmox03
    role: proxmox_ve
    exporter: cpu_temp_exporter
