# Monitor the Stack itself
- targets:
    - localhost:9090
  # Prometheus
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: prometheus

# Grafana
- targets:
    - grafana:3000
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: grafana

# Blackbox
- targets:
    - blackbox:9115
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: blackbox

# Alertmanager
- targets:
    - alertmanager:9093
  labels:
    tenant: internal
    environment: production
    role: control-plane
    service: alertmanager
