# Internal Monitoring - Monitoring the HOST VM
- targets:
    - node-exporter:9100
  labels:
    tenant: internal
    cluster: internal-monitoring-prod
    instance: monitoring-vm
    environment: production
    platform: docker
    role: control-plane
    host: monitoring-vm
    exporter: node

# Internal Server Monitoring - Cluster
# Prometheus Node Exporter for Bare Metal Servers

- targets:
    - 192.0.2.20:9100
  labels:
    tenant: irin
    cluster: irin-production
    instance: irin-svr01
    environment: production
    platform: metal
    host: irin-svr01
    role: irin-stack
    exporter: node

- targets:
    - 192.0.2.21:9100
  labels:
    tenant: irin
    cluster: irin-production
    instance: irin-svr02
    environment: production
    platform: metal
    host: irin-svr02
    role: irin-stack
    exporter: node

- targets:
    - 192.0.2.22:9100
  labels:
    tenant: irin
    cluster: irin-production
    instance: irin-dev01
    environment: production
    platform: metal
    host: irin-dev01
    role: irin-stack
    exporter: node

- targets:
    - 192.0.2.23:9100
  labels:
    tenant: irin
    cluster: irin-production
    instance: mtg-webserver
    environment: production
    platform: vm
    role: webserver
    host: mtg-webserver
    exporter: node

# RBI tenant
- targets:
    - 192.0.2.30:9100
  labels:
    tenant: rbi
    cluster: rbi-vm-prod
    instance: rbi-hail01
    environment: production
    platform: vm
    role: rbi-stack
    host: rbi-hail01
    exporter: node
