## --- Exporter for Proxmox Nodes ---

- targets:
    - 192.0.2.10:9221
  labels:
    tenant: Phoenix-Lab
    cluster: phoenix-lab-physical
    instance: pveBlack
    environment: server
    platform: proxmox_ve
    host: pveBlack
    role: proxmox_ve
    exporter: proxmox

#- targets:
#    - 192.0.2.11:9221
#  labels:
#    tenant: Phoenix-Lab
#    cluster: phoenix-lab-physical
#    instance: pveRed
#    environment: server
#    platform: proxmox_ve
#    host: pveRed
#    role: proxmox_ve
#    exporter: proxmox

#- targets:
#    - 192.0.2.12:9221
#  labels:
#    tenant: Phoenix-Lab
#    cluster: phoenix-lab-physical
#    instance: pveGreen
#    environment: server
#    platform: proxmox_ve
#    host: pveGreen
#    role: proxmox_ve
#    exporter: proxmox
