## SmartCTL Monitor for HomeLab and Production Servers

- targets:
    - 192.0.2.10:9633
  labels:
    tenant: homelab
    cluster: homelab-physical
    instance: proxmox01
    platform: proxmox_ve
    host: proxmox01
    role: proxmox_ve
    environment: production
    exporter: smartctl

- targets:
    - 192.0.2.11:9633
  labels:
    tenant: homelab
    cluster: homelab-physical
    instance: proxmox02
    platform: proxmox_ve
    host: proxmox02
    role: proxmox_ve
    environment: production
    exporter: smartctl

- targets:
    - 192.0.2.12:9633
  labels:
    tenant: homelab
    cluster: homelab-physical
    instance: proxmox03
    platform: proxmox_ve
    host: proxmox03
    role: proxmox_ve
    environment: production
    exporter: smartctl

- targets:
    - 192.0.2.20:9633
  labels:
    tenant: irin
    cluster: irin-production
    instance: irin-svr01
    platform: metal
    host: irin-svr01
    role: monitor-svr
    environment: production
    exporter: smartctl

- targets:
    - 192.0.2.21:9633
  labels:
    tenant: irin
    cluster: irin-production
    instance: irin-svr02
    platform: metal
    host: irin-svr02
    role: monitor-svr
    environment: production
    exporter: smartctl

- targets:
    - 192.0.2.22:9633
  labels:
    tenant: irin
    cluster: irin-production
    instance: irin-dev01
    platform: metal
    host: irin-dev01
    role: dev-svr
    environment: production
    exporter: smartctl
